ERROR 2025-09-13 04:14:19,710 log 18828 17500 Internal Server Error: /pos/
Traceback (most recent call last):
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 187, in _get_session
    return self._session_cache
           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: no existe la relación «django_session»
LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 489, in thread_handler
    raise exc_info[1]
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 489, in thread_handler
    raise exc_info[1]
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 439, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 493, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\contrib\auth\mixins.py", line 71, in dispatch
    if not request.user.is_authenticated:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\utils\functional.py", line 266, in inner
    self._setup()
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\utils\functional.py", line 419, in _setup
    self._wrapped = self._setupfunc()
                    ^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\contrib\auth\middleware.py", line 25, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\contrib\auth\middleware.py", line 11, in get_user
    request._cached_user = auth.get_user(request)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 191, in get_user
    user_id = _get_user_session_key(request)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 60, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
                                               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 53, in __getitem__
    return self._session[key]
           ^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 192, in _get_session
    self._session_cache = self.load()
                          ^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 42, in load
    s = self._get_session_from_db()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 32, in _get_session_from_db
    return self.model.objects.get(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\db\models\query.py", line 633, in get
    num = len(clone)
          ^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1560, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: no existe la relación «django_session»
LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...
                                                             ^

ERROR 2025-09-13 04:19:59,942 log 19700 18676 Internal Server Error: /pos/
Traceback (most recent call last):
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 187, in _get_session
    return self._session_cache
           ^^^^^^^^^^^^^^^^^^^
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.UndefinedTable: no existe la relación «django_session»
LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 489, in thread_handler
    raise exc_info[1]
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 489, in thread_handler
    raise exc_info[1]
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 439, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 493, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\contrib\auth\mixins.py", line 71, in dispatch
    if not request.user.is_authenticated:
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\utils\functional.py", line 266, in inner
    self._setup()
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\utils\functional.py", line 419, in _setup
    self._wrapped = self._setupfunc()
                    ^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\contrib\auth\middleware.py", line 25, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
                                            ^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\contrib\auth\middleware.py", line 11, in get_user
    request._cached_user = auth.get_user(request)
                           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 191, in get_user
    user_id = _get_user_session_key(request)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\contrib\auth\__init__.py", line 60, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
                                               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 53, in __getitem__
    return self._session[key]
           ^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\contrib\sessions\backends\base.py", line 192, in _get_session
    self._session_cache = self.load()
                          ^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 42, in load
    s = self._get_session_from_db()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\contrib\sessions\backends\db.py", line 32, in _get_session_from_db
    return self.model.objects.get(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\db\models\query.py", line 633, in get
    num = len(clone)
          ^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\db\models\query.py", line 380, in __len__
    self._fetch_all()
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\db\models\query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\db\models\query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1560, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\db\backends\utils.py", line 102, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\db\backends\utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.ProgrammingError: no existe la relación «django_session»
LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...
                                                             ^

ERROR 2025-09-13 04:23:13,979 log 11184 10132 Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 489, in thread_handler
    raise exc_info[1]
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 489, in thread_handler
    raise exc_info[1]
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\core\handlers\base.py", line 284, in _get_response_async
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 439, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 493, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\response.py", line 111, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\response.py", line 87, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\response.py", line 69, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: registration/login.html
ERROR 2025-09-13 04:23:25,797 log 11184 10132 Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 489, in thread_handler
    raise exc_info[1]
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 489, in thread_handler
    raise exc_info[1]
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\core\handlers\base.py", line 284, in _get_response_async
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 439, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 493, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\response.py", line 111, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\response.py", line 87, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\response.py", line 69, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: registration/login.html
ERROR 2025-09-13 04:23:46,925 log 11184 10132 Internal Server Error: /accounts/login/
Traceback (most recent call last):
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 489, in thread_handler
    raise exc_info[1]
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 489, in thread_handler
    raise exc_info[1]
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\core\handlers\base.py", line 284, in _get_response_async
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 439, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 493, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\response.py", line 111, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\response.py", line 87, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\response.py", line 69, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: registration/login.html
ERROR 2025-09-13 04:31:16,894 log 14096 11812 Internal Server Error: /pos/
Traceback (most recent call last):
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 489, in thread_handler
    raise exc_info[1]
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 489, in thread_handler
    raise exc_info[1]
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 439, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 493, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\core\pos\views.py", line 240, in get
    dolar = ValorDolar.objects.get(pk=1)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\db\models\query.py", line 637, in get
    raise self.model.DoesNotExist(
pos.models.ValorDolar.DoesNotExist: ValorDolar matching query does not exist.
ERROR 2025-09-13 04:31:27,631 log 14096 15724 Internal Server Error: /pos/
Traceback (most recent call last):
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 489, in thread_handler
    raise exc_info[1]
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 489, in thread_handler
    raise exc_info[1]
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 439, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 493, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\core\pos\views.py", line 240, in get
    dolar = ValorDolar.objects.get(pk=1)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\db\models\query.py", line 637, in get
    raise self.model.DoesNotExist(
pos.models.ValorDolar.DoesNotExist: ValorDolar matching query does not exist.
ERROR 2025-09-13 04:39:01,812 log 9720 9824 Internal Server Error: /pos/menu/dolar/1
Traceback (most recent call last):
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 489, in thread_handler
    raise exc_info[1]
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 489, in thread_handler
    raise exc_info[1]
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 439, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 493, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\core\pos\views.py", line 1840, in get
    return render(request, 'pos/valordolar_form.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'dolar' with no arguments not found. 1 pattern(s) tried: ['pos/menu/dolar/(?P<pk>[0-9]+)\\Z']
ERROR 2025-09-13 04:39:05,725 log 9720 9824 Internal Server Error: /pos/menu/dolar/1
Traceback (most recent call last):
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 489, in thread_handler
    raise exc_info[1]
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 489, in thread_handler
    raise exc_info[1]
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 439, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 493, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\core\pos\views.py", line 1840, in get
    return render(request, 'pos/valordolar_form.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'dolar' with no arguments not found. 1 pattern(s) tried: ['pos/menu/dolar/(?P<pk>[0-9]+)\\Z']
ERROR 2025-09-13 04:39:10,524 log 9720 9824 Internal Server Error: /pos/menu/
Traceback (most recent call last):
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 489, in thread_handler
    raise exc_info[1]
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 489, in thread_handler
    raise exc_info[1]
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 439, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 493, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\contrib\auth\mixins.py", line 135, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\core\pos\views.py", line 1194, in get
    return render(request, 'menu.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'dolar' with no arguments not found. 1 pattern(s) tried: ['pos/menu/dolar/(?P<pk>[0-9]+)\\Z']
ERROR 2025-09-13 04:39:10,654 log 9720 9824 Internal Server Error: /pos/menu/
Traceback (most recent call last):
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 489, in thread_handler
    raise exc_info[1]
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 489, in thread_handler
    raise exc_info[1]
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 439, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 493, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\contrib\auth\mixins.py", line 135, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\core\pos\views.py", line 1194, in get
    return render(request, 'menu.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'dolar' with no arguments not found. 1 pattern(s) tried: ['pos/menu/dolar/(?P<pk>[0-9]+)\\Z']
ERROR 2025-09-13 04:39:10,746 log 9720 9824 Internal Server Error: /pos/menu/
Traceback (most recent call last):
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 489, in thread_handler
    raise exc_info[1]
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 489, in thread_handler
    raise exc_info[1]
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 439, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 493, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\contrib\auth\mixins.py", line 135, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\core\pos\views.py", line 1194, in get
    return render(request, 'menu.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'dolar' with no arguments not found. 1 pattern(s) tried: ['pos/menu/dolar/(?P<pk>[0-9]+)\\Z']
ERROR 2025-09-13 04:39:18,723 log 9720 9824 Internal Server Error: /pos/menu/
Traceback (most recent call last):
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 489, in thread_handler
    raise exc_info[1]
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 489, in thread_handler
    raise exc_info[1]
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 439, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 493, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\contrib\auth\mixins.py", line 135, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\core\pos\views.py", line 1194, in get
    return render(request, 'menu.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'dolar' with no arguments not found. 1 pattern(s) tried: ['pos/menu/dolar/(?P<pk>[0-9]+)\\Z']
ERROR 2025-09-13 04:39:36,576 log 11272 19468 Internal Server Error: /pos/menu/
Traceback (most recent call last):
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 489, in thread_handler
    raise exc_info[1]
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 489, in thread_handler
    raise exc_info[1]
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 439, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 493, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\contrib\auth\mixins.py", line 135, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\core\pos\views.py", line 1194, in get
    return render(request, 'menu.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'dolar' with no arguments not found. 1 pattern(s) tried: ['pos/menu/dolar/(?P<pk>[0-9]+)\\Z']
ERROR 2025-09-13 04:39:39,176 log 11272 19468 Internal Server Error: /pos/menu/
Traceback (most recent call last):
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 489, in thread_handler
    raise exc_info[1]
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 489, in thread_handler
    raise exc_info[1]
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\core\handlers\base.py", line 253, in _get_response_async
    response = await wrapped_callback(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 439, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 493, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\contrib\auth\mixins.py", line 135, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\core\pos\views.py", line 1194, in get
    return render(request, 'menu.html', context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\template\defaulttags.py", line 471, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\urls\resolvers.py", line 828, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'dolar' with no arguments not found. 1 pattern(s) tried: ['pos/menu/dolar/(?P<pk>[0-9]+)\\Z']
ERROR 2025-09-13 05:14:07,469 log 9992 20304 Internal Server Error: /pos/api/productos/
ERROR 2025-09-13 05:14:17,699 log 9992 20304 Internal Server Error: /pos/api/productos/
ERROR 2025-09-13 05:14:33,407 log 12588 6900 Internal Server Error: /pos/api/productos/
ERROR 2025-09-15 22:17:51,257 log 12456 17424 Internal Server Error: /pos/api/productos/
ERROR 2025-09-15 22:21:10,404 log 19728 3988 Internal Server Error: /pos/api/productos/
ERROR 2025-09-30 14:46:57,607 log 3612 9424 Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 489, in thread_handler
    raise exc_info[1]
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\core\handlers\base.py", line 235, in _get_response_async
    callback, callback_args, callback_kwargs = self.resolve_request(request)
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\core\handlers\base.py", line 313, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\urls\resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\urls\resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\urls\resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\core\core\urls.py", line 15, in <module>
    path("pos/",include('pos.urls', namespace="pos")),
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\urls\conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\core\pos\urls.py", line 2, in <module>
    from .views import *
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\core\pos\views.py", line 2333
    categoria = CategoriasProductos.objects.get(pk=pk)
    ^^^^^^^^^
IndentationError: expected an indented block after 'try' statement on line 2332

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 489, in thread_handler
    raise exc_info[1]
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\utils\deprecation.py", line 150, in __acall__
    response = response or await self.get_response(request)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\core\handlers\exception.py", line 44, in inner
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 439, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 491, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\core\handlers\exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\core\handlers\exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\views\debug.py", line 67, in technical_500_response
    html = reporter.get_traceback_html()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\views\debug.py", line 410, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\views\debug.py", line 393, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\views\debug.py", line 100, in get_caller
    resolver_match = resolve(request.path)
                     ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\urls\base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\urls\resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\urls\resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\urls\resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\core\core\urls.py", line 15, in <module>
    path("pos/",include('pos.urls', namespace="pos")),
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\urls\conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\core\pos\urls.py", line 2, in <module>
    from .views import *
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\core\pos\views.py", line 2333
    categoria = CategoriasProductos.objects.get(pk=pk)
    ^^^^^^^^^
IndentationError: expected an indented block after 'try' statement on line 2332

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 489, in thread_handler
    raise exc_info[1]
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\utils\deprecation.py", line 150, in __acall__
    response = response or await self.get_response(request)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\core\handlers\exception.py", line 44, in inner
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 439, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 491, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\core\handlers\exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\core\handlers\exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\views\debug.py", line 67, in technical_500_response
    html = reporter.get_traceback_html()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\views\debug.py", line 410, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\views\debug.py", line 393, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\views\debug.py", line 100, in get_caller
    resolver_match = resolve(request.path)
                     ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\urls\base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\urls\resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\urls\resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\urls\resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\core\core\urls.py", line 15, in <module>
    path("pos/",include('pos.urls', namespace="pos")),
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\urls\conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\core\pos\urls.py", line 2, in <module>
    from .views import *
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\core\pos\views.py", line 2333
    categoria = CategoriasProductos.objects.get(pk=pk)
    ^^^^^^^^^
IndentationError: expected an indented block after 'try' statement on line 2332

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 489, in thread_handler
    raise exc_info[1]
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\utils\deprecation.py", line 150, in __acall__
    response = response or await self.get_response(request)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\core\handlers\exception.py", line 44, in inner
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 439, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 491, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\core\handlers\exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\core\handlers\exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\views\debug.py", line 67, in technical_500_response
    html = reporter.get_traceback_html()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\views\debug.py", line 410, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\views\debug.py", line 393, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\views\debug.py", line 100, in get_caller
    resolver_match = resolve(request.path)
                     ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\urls\base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\urls\resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\urls\resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\urls\resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\core\core\urls.py", line 15, in <module>
    path("pos/",include('pos.urls', namespace="pos")),
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\urls\conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\core\pos\urls.py", line 2, in <module>
    from .views import *
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\core\pos\views.py", line 2333
    categoria = CategoriasProductos.objects.get(pk=pk)
    ^^^^^^^^^
IndentationError: expected an indented block after 'try' statement on line 2332

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 489, in thread_handler
    raise exc_info[1]
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\utils\deprecation.py", line 150, in __acall__
    response = response or await self.get_response(request)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\core\handlers\exception.py", line 44, in inner
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 439, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 491, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\core\handlers\exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\core\handlers\exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\views\debug.py", line 67, in technical_500_response
    html = reporter.get_traceback_html()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\views\debug.py", line 410, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\views\debug.py", line 393, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\views\debug.py", line 100, in get_caller
    resolver_match = resolve(request.path)
                     ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\urls\base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\urls\resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\urls\resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\urls\resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\core\core\urls.py", line 15, in <module>
    path("pos/",include('pos.urls', namespace="pos")),
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\urls\conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\core\pos\urls.py", line 2, in <module>
    from .views import *
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\core\pos\views.py", line 2333
    categoria = CategoriasProductos.objects.get(pk=pk)
    ^^^^^^^^^
IndentationError: expected an indented block after 'try' statement on line 2332

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 489, in thread_handler
    raise exc_info[1]
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\core\handlers\exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\utils\deprecation.py", line 150, in __acall__
    response = response or await self.get_response(request)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\core\handlers\exception.py", line 44, in inner
    response = await sync_to_async(
               ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 439, in __call__
    ret = await asyncio.shield(exec_coro)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\asgiref\sync.py", line 491, in thread_handler
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\core\handlers\exception.py", line 140, in response_for_exception
    response = handle_uncaught_exception(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\core\handlers\exception.py", line 181, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\views\debug.py", line 67, in technical_500_response
    html = reporter.get_traceback_html()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\views\debug.py", line 410, in get_traceback_html
    c = Context(self.get_traceback_data(), use_l10n=False)
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\views\debug.py", line 393, in get_traceback_data
    c["raising_view_name"] = get_caller(self.request)
                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\views\debug.py", line 100, in get_caller
    resolver_match = resolve(request.path)
                     ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\urls\base.py", line 24, in resolve
    return get_resolver(urlconf).resolve(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\urls\resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\urls\resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\utils\functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\urls\resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\core\core\urls.py", line 15, in <module>
    path("pos/",include('pos.urls', namespace="pos")),
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\venv\Lib\site-packages\django\urls\conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\core\pos\urls.py", line 2, in <module>
    from .views import *
  File "C:\Users\Alejandro Sarmiento\Desktop\scg-estandar\scg\core\pos\views.py", line 2333
    categoria = CategoriasProductos.objects.get(pk=pk)
    ^^^^^^^^^
IndentationError: expected an indented block after 'try' statement on line 2332
